export const tiere = [
    { img: "/src/assets/images/tiere/ace_stick.jpg" },
    { img: "/src/assets/images/tiere/milto.jpeg" },
    { img: "/src/assets/images/tiere/olaf1.jpeg" },
    { img: "/src/assets/images/tiere/katze1.jpeg" },
    { img: "/src/assets/images/tiere/katze3.jpeg" },
    { img: "/src/assets/images/tiere/frenchis.jpeg" },
    { img: "/src/assets/images/tiere/katze4.jpeg" },
    { img: "/src/assets/images/tiere/frenchie.jpeg" },
    { img: "/src/assets/images/tiere/katze5.jpeg" },
    { img: "/src/assets/images/tiere/katzen.jpeg" },
    { img: "/src/assets/images/tiere/vito1.jpg" },
    { img: "/src/assets/images/tiere/vito3.jpg" },
    { img: "/src/assets/images/tiere/vito4.jpg" },
    { img: "/src/assets/images/tiere/vito5.jpg" },
    { img: "/src/assets/images/tiere/nelly_liegt.jpeg" },
    { img: "/src/assets/images/tiere/nelly_bailey.jpg" },
    { img: "/src/assets/images/tiere/bailey.jpg" },
    { img: "/src/assets/images/tiere/kaninchen.jpg" },
    { img: "/src/assets/images/tiere/kathi_kaninchen.jpg" },
    { img: "/src/assets/images/tiere/kathi_maus.jpg" },
    { img: "/src/assets/images/tiere/lotte_auf_decke.jpeg" },
    { img: "/src/assets/images/tiere/lotte_auf_stuhl.jpeg" },
];
